version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: service-booking-system-app
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - sbssystem-network
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: service-booking-system-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sbssystem-network

  mysql:
    image: mysql:8.0
    container_name: service-booking-system-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: service_booking_system
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sbssystem-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql
    networks:
      - sbssystem-network

volumes:
  mysql-data:

networks:
  sbssystem-network:
    driver: bridge
